### ISSUE TITLE
Endpoint (GET): Sted valgt i kart  - Vurderingsstatistikk hentes ut.

### ISSUE THREAD

**Issue by rmykle** [Knowit-Objectnet/hlf#16]
Ved hjelp av placeID skal det hentes ut statistikk på de fire ulike kategoriene når bruker har valgt et sted i kartet. Det er ikke behov for kommentarer, kun antall positive og negative stemmer per kategori. 

Kanskje foretrukket om det kun er en vurdering per bruker i tilfeller hvor det er flere (nyeste).
Endepunktet kan gjerne også ha et flag som parameter gjør det mulig å inkludere google-data om stedet i samme kall.

Med andre ord ønskelig med noe ala:
placeid -> 
{
reviews: {
information: {
positive: 2,
negative: 1
etc etc
}, // hvis googleData = true
googleData: {
formatted_address: "Karl johans gate 3"
etc
}
}

**Comment by mariahilmojensen** [comment]
Implementert i StedController som getTotalvurderingForSted.

URI: /steder/place/{placeId}/totalvurdering/{googleinfo} 
hvor googleinfo er enten 1 eller 0 og angir om googledata om stedet skal inkluderes eller ikke.
