### ISSUE TITLE
Endpoint (GET): Hente ut vurderinger på et gitt sted

### ISSUE THREAD

**Issue by rmykle** [Knowit-Objectnet/hlf#17]
Mulighet til å hente ut en liste over vurderinger på en gitt placeid, sortert og gjerne paginert. 
Tenker det kan være greit at vurderinger fra samme bruker på samme dag havner sammen i ett objekt, men om ulike vurderingskriterier utføres på forskjellige dager (av samme bruker) er de ulike objekter.

Eks: 
placeid -> 
{
reviews: [
{date: 1/1/1991,
types: {
information: {
positive: true,
comment: "bra"
}
}
}.....]
}

**Comment by mariahilmojensen** [comment]
Implementert i VurderingController som getVurderingerByPlaceId.
URI: /vurderinger/placeId/{placeId}

Endepunktet henter ut vurderinger som er gjort på et gitt sted. Resultatet er paginert med default 40 vurderinger (dette er valgt slik at 10 totale vurderinger vil kunne vises). Dersom andre verdier ønskes spesifiser i URIen på følgende måte: /vurderinger/placeId/{placeId}?page=0&size=20 f.eks.

Vurderinger gjort av samme bruker på samme dag blir slått sammen. Resultatet er på følgende format: 
    [   {
        "dato": "2018-07-18",
        "registrator": 2, (eller hele objectet)
        "vurderinger": {
            "teleslynge": {"kommentar": "Noe", "rangering": true},
            "lydforhold": {"kommentar": "Noe annet", "rangering": false},
            ...
            }
        },
        {
        "dato": "2018-07-17",
        "registrator": 3,
        ...
        },
        ...
    ]
