### ISSUE TITLE
Endpoint (GET): Endepunkt for å hente ut brukerens eksisterende vurderinger av et sted.

### ISSUE THREAD

**Issue by rmykle** [Knowit-Objectnet/hlf#18]
Endepunkt for å hente ut brukerens eksisterende vurderinger av et sted.
brukerid & placeid -> {
information: {
positive:false,
comment:"dårlig",
etc etc.
}

**Comment by rmykle** [comment]
Endepunkt for å hente ut brukerens eksisterende vurderinger av et sted. 
brukerid & placeid -> {
information: {
positive:false,
comment:"dårlig",
etc etc.
}

**Comment by mariahilmojensen** [comment]
Implementert i VurderingController som getVurderingerByPlaceIdAndBrukerId.
URI: /vurderinger/placeId/{placeId}/brukerId/{brukerId}

Returnerer en liste med vurderinger (altså hvis en bruker har vurdert alle de fire forholdene ved et sted, vil lista bestå av fire elementer).

**Comment by lisamso** [comment]
Endret getVurderingerByPlaceIdAndBruker, slik at brukerId hentes automatisk ved å ta inn access_token.
URI: /vurderinger/placeId/{placeId}/bruker

Returnerer det samme som tidligere.

**Comment by rmykle** [comment]
Gjenåpner. Er nødt å vite hva slags vurdering som er gitt. Er ingen måte å se om det er snakk om teleslynge, informasjon osv. 
[
	{
		"id": 1,
		"sted": {
			"id": 1,
			"placeId": "ChIJFVLTKWduQUYRK4owC-eIqBg"
		},
		"registrator": {
			"id": 1,
			"auth0UserId": "google-oauth2|106354146952404655918",
			"fornavn": "Rune ",
			"etternavn": "Myklevoll",
			"imageUrl": "https//lh4.googleusercontent.com/-e6BpASBn-b8/AAAAAAAAAAI/AAAAAAAAAAA/AAnnY7rqqoIYcV1wTdXxJurRRh4GHSAg2A/mo/photo.jpg"
		},
		"dato": "2018-07-25",
		"kommentar": "kan bli bedre",
		"rangering": true
	},
	{
		"id": 2,
		"sted": 1,
		"registrator": 1,
		"dato": "2018-07-25",
		"kommentar": "kan bli bedre #2",
		"rangering": true
	}
]

**Comment by mariahilmojensen** [comment]
Det inkluderes nå en "type" som sier hva slags vurdering det er snakk om. F.eks.
{
   "type": "Teleslyngevurdering",¨
    "id": 30, 
   ...
}
