### ISSUE TITLE
Endpoint (PUT): Legge inn en vurdering på et kriterie på et gitt sted (et kriterie av gangen)

### ISSUE THREAD

**Issue by rmykle** [Knowit-Objectnet/hlf#19]
Endepunkt for å legge inn en vurdering av et kriterie på et bestemt sted. Endepunktet kan også være POST, avhengig av hvilken strategi som er greiest å gjennomføre (lage ny eller oppdatere). Spiller i utgangspunktet ingen rolle for frontend, så lenge det er reflektert i andre endpoints.

Hvis stedet ikke eksisterer fra før i databasen er det litt essensielt at det opprettes ved å kun benytte placeid (appen har ingen enkel måte å vite hva database-id er).  

I utgangspunktet kan dette deles inn i fire forskjellige endpoint om det er greiest, hvis ikke kan appen sende type som parameter.

**Comment by mariahilmojensen** [comment]
Legge inn vurdering er implementert i alle underklassene for vurdering som createXXXvurdering. Dersom en vurdering skal opprettes finnes metoder for updateXXXvurdering som krever tilgang til vurderingens id (som returneres når metoden getVurderingerByPlaceIdAndBrukerId brukes). 

Grundigere forklaring: 
Etter totalvurdering for et sted er funnet (første kall) har frontend tilgang til id'en et sted har i vår database. Dersom stedet med en id ikke er lagret i vår db, får man NULL her.

En vurdering opprettes ved å (blant annet) referere med id til et allerede eksisterende sted, eller ved å opprette et nytt sted med en placeId. Resultatet fra det forrige kallet skal altså brukes her. Vi kan ta få to ulike kall:
Allerede eksisterende sted:
{
    "sted": {"id": 1},
    "registrator": {"id": 2},
    ...
}
Sted som ikke er i vår db:
{
    "sted": {"placeId": "ChIJOT0lHIpuQUYRF6qkr3nXDeg"},
    ...
}
------------------------------------------------------------------------------------
Når et sted skal **endres** skal input være slik:
{
    "kommentar": "Positiv kommentar",
    "rangering": true
}
Dato endres til nåværende dato, og bruker samt sted forblir det samme som tidligere.

**Comment by mariahilmojensen** [comment]
Legge inn vurdering er implementert i alle controller-underklassene for vurdering som createXXXvurdering. Dersom en vurdering skal oppdateres finnes metoder for updateXXXvurdering som krever tilgang til vurderingens id (som returneres når metoden getVurderingerByPlaceIdAndBrukerId brukes).

**Grundigere forklaring:**
En vurdering opprettes ved å referere til et sted med en placeId, og med id til en bruker. Rangering må settes, mens kommentar kan droppes dersom ønskelig. Dette gjøres på følgende måte:
{
	"sted": {"placeId": "ChIJOT0lHIpuQUYRF6qkr3nXDeg"},
	"registrator": {"id": 3},
	"kommentar": "testkommentar",
	"rangering": true
}
evt.
{
	"sted": {"placeId": "ChIJOT0lHIpuQUYRF6qkr3nXDeg"},
	"registrator": {"id": 3},
	"rangering": true
}

Dersom stedet ikke finnes fra før vil det opprettes i databasen, og dersom det finnes vil denne vurderingen legges til i listen "vurderinger" i stedet. 

Når et sted skal endres skal input være slik:
{
	"kommentar": "Positiv kommentar",
	"rangering": true
}
Dato endres til nåværende dato, og bruker samt sted forblir det samme som tidligere.

**Comment by lisamso** [comment]
Endret endepunktene slik at createXXXvurdering ikke trenger å ta inn registrator, da denne vil bli hentet ved å bruke access_token. Dersom den er med i request body, vil den likevel bli skrevet over.

**Comment by mariahilmojensen** [comment]
Endret slik at det kun er én metode for oppretting, createVurdering (i VurderingContolller). Her må hvilken type vurdering det er spesifiseres. Typen kan enten være "Teleslyngevurdering", "Lydforholdvurdering", "Lydutjevningvurdering" eller "Informasjonvurdering".

F.eks.:
{
    "type": "Teleslyngevurdering",
    "sted": {"placeId": "ChIJOT0lHIpuQUYRF6qkr3nXDeg"},
    "registrator": {"id": 3},
    "kommentar": "testkommentar",
    "rangering": true 
}
