### ISSUE TITLE
Ordne DNS og sette opp SSL

### ISSUE THREAD

**Issue by andedah** [Knowit-Objectnet/hlf#25]
Ordne DNS for forskjellige miljøer. 
Ruting må Thomas hos HLF gjøre. 
Vi trenger i første omgang `test.api.godlyd.no` og `api.godlyd.no`. 

Det er også viktig å få satt opp SSL (HTTPS). 
For å få til dette må det settes opp en Nginx config for rute all trafikk som kommer på HTTP tilbake til lastbalansereren på HTTPS. Se: https://blog.realkinetic.com/http-to-https-using-google-cloud-load-balancer-dda57ac97c

Nginx skal konfigureres med Packer

**Comment by andedah** [comment]
Se her for en guide på hvordan vi kan ordne SSL: https://geekflare.com/google-load-balancer-enable-ssl/

Noe dokumentasjon hos GCP: https://cloud.google.com/load-balancing/docs/https/

Oppdater Terraform config slik at SSL ordnes derifra. Se dokumentasjon for dette her: https://www.terraform.io/docs/providers/google/r/compute_ssl_certificate.html
https://www.terraform.io/docs/providers/google/r/compute_target_https_proxy.html

**Comment by sirhaug** [comment]
Løst i commit 36c344b36aeb5af7909287c30486de546431645a
