### ISSUE TITLE
Fjerne secrets fra Github

### ISSUE THREAD

**Issue by andedah** [Knowit-Objectnet/hlf#28]
Det ligger noen secrets i properties filene sjekket inn på github. 
Disse må fjernes og nye må genereres. 

Alle secrets bør hentes dynamisk fra en eller flere tekstfil(er) liggende i en kryptert i _google cloud storage_

https://cloud.google.com/kms/docs/store-secrets

**Comment by lisamso** [comment]
Secrets hentes nå fra en kryptert fil og injectes når docker imaget bygges. Se doc.md for instruksjoner
