### ISSUE TITLE
Automatisk deployment

### ISSUE THREAD

**Issue by andedah** [Knowit-Objectnet/hlf#3]
Finne en måte å gjøre automatisk deployment av docker container

Mulig utgangspunkt: 
https://cloud.google.com/compute/docs/containers/deploying-containers (_Men er i beta og kan i fremtiden ende med å bli deprecated_)

**Comment by rmykle** [comment]
Kommando som er nevnt i cloud-readmen på git ser ikke ut til å fungere som den skal (siste steget altså, push fungerer tilsynelatende som det skal). 

Ny strategi bør derfor søkes etter for å kjøre image etter opplasting til Container registry.

**Comment by lisamso** [comment]
Lagde et python script som pusher containeren.
