### ISSUE TITLE
Lage custom 404 som skiller fravær av resources til ikke eksisterende endepunkt

### ISSUE THREAD

**Issue by rmykle** [Knowit-Objectnet/hlf#31]

**Comment by mariahilmojensen** [comment]
ResourceNotFoundException (404) kastes når man prøver å aksessere noe i databasen som ikke er der. F.eks. hvis man prøver å hente ut et sted med en placeId som ikke er der, får man unntak med meldingen: "Sted not found with placeId: 'innsatt placeId"". 
MERK: unntaket kastes kun dersom det bare skal returneres én vurdering, ett sted eller én bruker. Dersom endepunktet man tilkaller returnerer en liste, vil man bare få en tom liste dersom det ikke er noe som samsvarer i databasen. 

Dersom man skriver feil uri vil man få et standard 404 exception.
