### ISSUE TITLE
Lage innhold til profilsliden

### ISSUE THREAD

**Issue by rmykle** [Knowit-Objectnet/hlf#34]
For tiden et tomrom i profilsliden i appen som kan fylles av noe fornuftig, siste anmeldelser e.l.
API må muligens skrives opp noe, da den ikke vet navnet på de ulike stedene, og uten dette er det vrient å lage noe saklig data (id-er har ingen semantisk verdi).

**Comment by osvold** [comment]
Denne er løst. Lukker
