### ISSUE TITLE
Legge til timestampfilter på endepunktet som henter ut vurderinger fra et sted

### ISSUE THREAD

**Issue by lisamso** [Knowit-Objectnet/hlf#40]
Endepunktet som henter ut alle vurderinger til et sted bør kunne ta inn et timestamp som en parameter, og kun hente ut vurderinger som er nyere enn dette timestampet.

**Comment by sirhaug** [comment]
Et raskt søk i frontend (alle filer i `app`-mappen) viser at endepunktet med paginering `/vurderinger/place/{placeId}` brukes til fordel for `/vurderinger/all/place/{placeId}`, da sistnevnte ikke blir brukt i det hele tatt.

Paginering er i skrivende stund ikke implementert i frontend.

En diskusjon bør tas ang hvilke endepunkter som skal brukes, og om det evt er planlagt paginering i frontend.
