### ISSUE TITLE
Sentralisert logging

### ISSUE THREAD

**Issue by andedah** [Knowit-Objectnet/hlf#6]
Sette opp et system for å sentralisere og lagre logging

**Comment by mariahilmojensen** [comment]
Stackdriver logging er aktivert vba. gcplogs-docker-driver. Loggen kan vises ved å:

1. Gå til **Logging** > Logs under STACKDRIVER i GCP navigasjonsmenyen. 
2. I det øverste tekstfeltet, trykk på pilen i høyre hjørnet. Velg "Convert to advanced filter".
3. Skriv inn følgende, og submit filter:
```
resource.type="global"
 logName="projects/godlydpatruljen/logs/gcplogs-docker-driver"
("data")
```

Alle entry-ene som dukker opp her blir logget av Docker og inneholder feltet jsonPayload.data som tilsvarer én linje i outputen ved kjøring.
